name: Flutter Tests

on:
  push:
    branches: [ main, develop, 'release/**' ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  flutter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.2'
          channel: 'stable'
          cache: true

      - name: Verify Flutter installation
        run: |
          flutter --version
          flutter doctor -v

      - name: Run Flutter package tests
        working-directory: packages/flutter
        run: |
          flutter pub get
          flutter test

      - name: Run Flutter example tests
        working-directory: examples/flutter_example
        run: |
          flutter pub get
          flutter analyze
          flutter test

    # Don't include these until we run on MacOS runners - x86 will be deprecated soon
      # - name: Build Flutter example (Android)
      #   working-directory: examples/flutter_example
      #   run: flutter build apk --debug
