name: Release Please

# Alternative automated release workflow using Google's Release Please
# This creates release PRs automatically based on conventional commits

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: false # Set to true to enable this workflow
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: agenteract
          monorepo-tags: true

      # Only run publish step if a release was created
      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Setup pnpm
        if: ${{ steps.release.outputs.release_created }}
        uses: pnpm/action-setup@v4
        with:
          version: 10.9.0

      - name: Setup Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm install --frozen-lockfile

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm run build

      - name: Publish to NPM
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm -r --filter "@agenteract/*" exec npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

